[package]
name = "keccak256"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
sha3 = "0.10.6"
proptest = "1.2.0"
noir-runner = { git = "https://github.com/noir-lang/noir-runner", branch = "main" }
